### ISSUE TITLE
Widget Fails to Load, No Error

### ISSUE THREAD

**Issue by RyanYags** [Nifty255/Bit-Boss-Battles#18] opened 2017-03-28 03:51 UTC
Hi Nifty, first let me say thank you for this amazing little tool! Both chat and myself love it!

I've been using Bit Boss Battles for a little while with no issues.  But today, it stopped working out of no where. 

The widget is exactly what I want, but what I get on my layout is not what is in the widget. On the widget it is transparent, has 500 HP, has me as the boss and all the other settings I set up. But in OBS it is not transparent, has no name and has 1000 HP. I have already re launched, deleted my CLR browser and put it back in, and totally reset everything twice, but I always get this no transparency, no name, 100HP version on my lay out. What can I do?

**Comment by Nifty255** [comment] 2017-03-28 03:52
Does your OBS version say 0/1000? Or does it start like normal but without a name?

**Comment by RyanYags** [comment] 2017-03-28 03:58
Yes, 0/1000 and no name, here is a screen shot: http://imgur.com/a/UknnH

**Comment by Nifty255** [comment] 2017-03-28 03:59
Some users are experiencing similar issues which I am currently unable to reproduce. At the moment, I'm working on a separate issue, but if you'd like to help me test yours later, I'd very much appreciate it.

**Comment by RyanYags** [comment] 2017-03-28 04:00
As long as I am not asleep i can try to help :)

**Comment by Imperialgrrl** [comment] 2017-03-29 16:04
Hi! I'm having the same exact problem - 0/1000 but the widget shows it like it should be working. I'm using Xsplit, and I'm happy to help you troubleshoot!

**Comment by Nifty255** [comment] 2017-03-29 16:39
Thank you Imperialgrrl for offering! I am free in 5 hours for troubleshooting, for up to 5 hours. Please DM me on Twitter for a method of contact (email, Skype, Discord).

**Comment by Nifty255** [comment] 2017-03-31 01:21
This issue has been found to be associated solely with OBS Classic, as the CLR Browser plugin runs Chrome 37 (a very old version), which doesn't support Javascript's "let"identifier. Update coming shortly.

**Comment by Imperialgrrl** [comment] 2017-03-31 15:41
FYI - I am still having this issue as of my latest verification right now. I am using XSplit.

**Comment by Nifty255** [comment] 2017-03-31 15:45
Other users of XSplit have found that manually updating their software has fixed the issue. If that is not an option, a bug was recently found and fixed in the reset link on BBB's site. If you haven't tried resetting lately, please try again.

**Closed** 2017-04-01 06:56 UTC
Labels: bug
